# Generated by Django 5.1.6 on 2025-02-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('vip', 'VIP'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='qeY6ANGymfgfNNFTT7XWP9fncA71Pc7N', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='E27un0UyWNMCdzK6VQ0mbALY4948H1tw', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
