# Generated by Django 5.1.6 on 2025-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_address_remove_user_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='hURP3MKuGKT1dOIGA4gGn742vQ0p83yR', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='Y0fnKjAuqLHLGgA2FyicS8AJeaAMaM7L', max_length=32, unique=True),
        ),
    ]
