# Generated by Django 5.1.6 on 2025-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_ref_link_1_alter_user_ref_link_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='b3uBHcU5rZPiE3lqbqI9YJJKzopPaP2O', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='KWNWoRk41ywH4b4ahTOY56ofjnlqVDRv', max_length=32, unique=True),
        ),
    ]
