# Generated by Django 5.1.6 on 2025-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_alter_user_ref_link_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('menu_type', models.CharField(choices=[('home', 'Главная'), ('career', 'Моя карьера'), ('team', 'Моя команда'), ('promo', 'Промо и розыгрыши'), ('news', 'Новости и публикации'), ('ads', 'Рекламные материалы'), ('profile', 'Мой профиль'), ('orders', 'Мои заказы'), ('wallet', 'Мой кошелек'), ('docs', 'Документы компании'), ('support', 'Поддержка')], max_length=10)),
                ('is_main_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='QuKIHvmUBlVeyzXTyE3GLgOgbW80n5Me', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='GILeBBxscW2Qisa5qMhghqljWe3Ft4zN', max_length=32, unique=True),
        ),
    ]
