# Generated by Django 5.1.6 on 2025-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_menuitem_alter_user_ref_link_1_alter_user_ref_link_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_status',
            field=models.BooleanField(default=False, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='user',
            name='binary_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Значение бинарного счета'),
        ),
        migrations.AddField(
            model_name='user',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='PV (power value)'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.IntegerField(choices=[(0, 'Status 0'), (1, 'Status 1'), (2, 'Status 2'), (3, 'Status 3'), (4, 'Status 4'), (5, 'Status 5'), (6, 'Status 6'), (7, 'Status 7'), (8, 'Status 8'), (9, 'Status 9')], default=0, verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Значение кошелек'),
        ),
        migrations.AlterField(
            model_name='user',
            name='partner_type',
            field=models.CharField(choices=[('start', 'Start'), ('smart', 'Smart'), ('senior', 'Senior'), ('sovereign', 'Sovereign'), ('stellar', 'Stellar')], default='start', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='APdjsjrd1fLTXzKdesOa5OsSkUcdFhrK', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='tak5DLuFRI1oxT4xFEpVVtExVQpxR3LU', max_length=32, unique=True),
        ),
    ]
