# Generated by Django 5.1.6 on 2025-02-25 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marketingplan_alter_user_ref_link_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='7jQHcX3UhOZucZWebofslSvmrfeRfZKc', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='TwsC1E6LNjUCggEfEqRoSQijz2xJb4RJ', max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='TeamPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], help_text='Сторона в бинарном дереве (L — левая, R — правая)', max_length=1)),
                ('level', models.PositiveIntegerField(default=1, help_text='Уровень (глубина) реферала в ветке относительно данного sponsor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(help_text='Реферал (новый пользователь)', on_delete=django.db.models.deletion.CASCADE, related_name='placements_as_child', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(help_text='Пользователь, под которым находится реферал', on_delete=django.db.models.deletion.CASCADE, related_name='placements_as_sponsor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
