# Generated by Django 5.1.6 on 2025-03-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_ref_link_1_alter_user_ref_link_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplacement',
            name='marketing_activity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamplacement',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='Уровень (глубина) реферала в ветви относительно данного sponsor'),
        ),
        migrations.AlterField(
            model_name='teamplacement',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], help_text='Сторона в бинарном дереве (L – левая, R – правая)', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_1',
            field=models.CharField(default='D1bFDGTZWBK04DiXSF2sOqsLk98rhWN0', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_link_2',
            field=models.CharField(default='t9pcv3RHb4H93eCrpTkfpDM4sKvv44vE', max_length=32, unique=True),
        ),
    ]
